version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: aise_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: aise_admin
      POSTGRES_PASSWORD: aise_password
      POSTGRES_DB: aise_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: aise_postgres_data
