from typing import Protocol, Optional
from src.domain.order import Order

class OrderRepository(Protocol):
    def save(self, order: Order) -> None: ...
    def get_by_id(self, id: str) -> Optional[Order]: ...
    def delete(self, id: str) -> None: ...
